#!/bin/sh

echo "Checking for an older version of mmPicons in the system..."
if [ -d /usr/lib/enigma2/python/Plugins/Extensions/mmPicons ]
then
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/mmPicons > /dev/null 2>&1
fi
echo "Plugin removed! You should restart enigma2 now!"
exit 0
